baseURL = ""
title = "clburlison"
paginate = 10
theme = "PaperMod"
enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false
pygmentsUseClasses = true

[permalinks]
  post = "/:title/"
  page = "/:title/"

[minify]
disableXML = true
minifyOutput = true

[params]
env = "production"
title = "clburlison"
description = "Clayton Burlison's personal blog."
keywords = [ "Blog", "Tech" ]
DateFormat = "January 2, 2006"
defaultTheme = "auto"
disableThemeToggle = false
ShowReadingTime = true
ShowShareButtons = false
ShowPostNavLinks = false
ShowBreadCrumbs = false
ShowCodeCopyButtons = true
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
comments = false
hidemeta = false
hideSummary = true
showtoc = false
tocopen = false

  [params.label]
  text = "clburlison"
  icon = "/apple-touch-icon.png"
  iconHeight = 35

  [params.profileMode]
  enabled = false

  [params.homeInfoParams]
  Title = "Hi there 👋"

  [[params.socialIcons]]
  name = "github"
  url = "https://github.com/clburlison"

  [[params.socialIcons]]
  name = "mastodon"
  url = "https://mastodon.social/@clburlison"

  [[params.socialIcons]]
  name = "linkedin"
  url = "https://linkedin.com/in/clburlison"

  [[params.socialIcons]]
  name = "twitter"
  url = "https://twitter.com/clburlison"

  [params.cover]
  hidden = true
  hiddenInList = true
  hiddenInSingle = true

  [params.editPost]
  URL = "https://github.com/clburlison/clburlison.com/edit/main/content/"
  Text = "Suggest Changes"
  appendFilePath = true

  [params.fuseOpts]
  isCaseSensitive = false
  shouldSort = true
  location = 0
  distance = 1_000
  threshold = 0.4
  minMatchCharLength = 0
  keys = [ "title", "permalink", "summary", "content" ]

[[menu.main]]
identifier = "about"
name = "about"
url = "/about/"
weight = 10

[[menu.main]]
identifier = "archives"
name = "archives"
url = "/archives/"
weight = 10

[[menu.main]]
identifier = "search"
name = "search"
url = "/search"
weight = 30

[markup.highlight]
noClasses = false

[outputFormats.RSS]
baseName = "feed"

[outputs]
home = [ "HTML", "RSS", "JSON" ]