source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-sitemap'
# gem 'octopress', '~> 3.0.0.rc.12'
gem 'rake', '~> 10.0'
gem 'stringex', '~> 1.4.0'
gem 'travis'
gem 'nokogiri'
# gem 'flickraw'
# gem 'dalli'
gem 'mini_magick'
gem 'jekyll-redirect-from'

gem 'RedCloth'
gem 'rdiscount'
gem 'kramdown'
gem 'redcarpet'