source 'https://rubygems.org'

gem 'jekyll'
gem 'jekyll-redirect-from'
gem 'jekyll-sitemap'
gem 'jekyll-gist'
gem 'rake'
gem 'stringex'
gem 'travis'

# Not currently in usage
# gem 'nokogiri'
# gem 'flickraw'
# gem 'dalli'
# gem 'mini_magick'
# gem 'octopress', '~> 3.0.0.rc.12'
# gem 'RedCloth'
# gem 'rdiscount'
gem 'kramdown'
# gem 'redcarpet'
# gem 'jekyll-compose'